# Generated by Django 2.2 on 2023-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报名管理',
                'verbose_name_plural': '报名管理',
            },
        ),
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('openid', models.CharField(max_length=28, verbose_name='openid')),
                ('startDate', models.CharField(max_length=8, verbose_name='发车日期')),
                ('startTime', models.CharField(max_length=5, verbose_name='发车时间')),
                ('timestamp', models.CharField(max_length=13, verbose_name='发车时间戳')),
                ('station', models.CharField(choices=[('太原南站', '太原南站'), ('太原站', '太原站'), ('武宿机场', '武宿机场')], default='太原南站', max_length=5, verbose_name='乘车站点')),
                ('state', models.CharField(choices=[('0', '报名中'), ('1', '被申请'), ('2', '满员'), ('3', '完成拼车'), ('4', '已解散')], max_length=1, verbose_name='状态码')),
                ('maxNum', models.SmallIntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default=2, verbose_name='最大人数')),
                ('currentNum', models.SmallIntegerField(default=1, verbose_name='现在人数')),
            ],
            options={
                'verbose_name': '拼车队列',
                'verbose_name_plural': '拼车队列',
            },
        ),
    ]
