# Generated by Django 2.2 on 2022-05-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20, verbose_name='发布时间')),
                ('images', models.TextField(verbose_name='图片列表')),
                ('content', models.TextField(verbose_name='说说内容')),
                ('visitor', models.IntegerField(verbose_name='浏览量')),
                ('spiderDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '科大热点',
                'verbose_name_plural': '科大热点',
            },
        ),
    ]
