# Generated by Django 2.2 on 2022-05-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='表白墙名称'),
        ),
        migrations.AddField(
            model_name='feed',
            name='number',
            field=models.CharField(default='', max_length=15, verbose_name='QQ号'),
        ),
    ]
