# Generated by Django 2.2 on 2022-05-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_hotspot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='number',
            field=models.CharField(default='', max_length=15, verbose_name='QQ号'),
        ),
    ]
