# Generated by Django 2.2 on 2022-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_hotspot_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='name',
            new_name='origin',
        ),
        migrations.AddField(
            model_name='feed',
            name='commerce',
            field=models.BooleanField(default=False, verbose_name='商业热搜'),
        ),
        migrations.AddField(
            model_name='feed',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='推荐热搜'),
        ),
        migrations.AddField(
            model_name='feed',
            name='tag',
            field=models.CharField(default='hot', max_length=10, verbose_name='信息类型'),
        ),
        migrations.AddField(
            model_name='feed',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='热点标题'),
        ),
        migrations.AddField(
            model_name='feed',
            name='top',
            field=models.BooleanField(default=False, verbose_name='置顶热搜'),
        ),
    ]
