# Generated by Django 2.2 on 2022-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20220511_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='spiderDate',
            field=models.DateTimeField(auto_now=True, verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='tag',
            field=models.CharField(choices=[('hot', '热点'), ('article', '文章')], default='hot', max_length=10, verbose_name='信息类型'),
        ),
    ]
