# Generated by Django 2.2 on 2022-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20220512_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='origin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='表白墙名称'),
        ),
    ]
