# Generated by Django 2.2 on 2022-05-19 06:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20220517_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='说说内容'),
        ),
    ]
