# Generated by Django 2.2 on 2022-06-06 09:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20220519_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20, verbose_name='发布时间')),
                ('title', models.CharField(default='', max_length=20, verbose_name='热点标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='说说内容')),
                ('visitor', models.IntegerField(verbose_name='浏览量')),
                ('spiderDate', models.DateTimeField(auto_now=True, verbose_name='爬取时间')),
                ('origin', models.CharField(blank=True, max_length=20, null=True, verbose_name='新闻来源')),
                ('cover', models.CharField(max_length=200, verbose_name='封面链接')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='原文链接')),
                ('recommend', models.BooleanField(default=False, verbose_name='推荐热搜')),
                ('commerce', models.BooleanField(default=False, verbose_name='商业热搜')),
                ('top', models.BooleanField(default=False, verbose_name='置顶热搜')),
                ('tag', models.CharField(choices=[('hot', '热点'), ('article', '文章')], default='article', max_length=10, verbose_name='信息类型')),
            ],
            options={
                'verbose_name': '学校新闻',
                'verbose_name_plural': '学校新闻',
            },
        ),
    ]
