# Generated by Django 2.2 on 2022-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='tag',
            field=models.CharField(choices=[('hot', '热点'), ('news', '新闻'), ('article', '文章')], default='hot', max_length=10, verbose_name='信息类型'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('hot', '热点'), ('news', '新闻'), ('article', '文章')], default='news', max_length=10, verbose_name='信息类型'),
        ),
    ]
