# Generated by Django 2.2 on 2023-02-04 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('create_timestamp', models.CharField(max_length=10, verbose_name='创建时间戳')),
                ('object_type', models.SmallIntegerField(blank=True, choices=[('博客', 0), ('文章', 1), ('视频', 2), ('评论', 3)], null=True, verbose_name='行为对象类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='行为对象ID')),
                ('action_type', models.SmallIntegerField(blank=True, choices=[('浏览', 0), ('点赞', 1), ('转发', 2), ('评论', 3), ('收藏', 4), ('跟随', 5), ('发布', 6)], null=True, verbose_name='行为类型')),
            ],
            options={
                'verbose_name': '行为日志',
                'verbose_name_plural': '行为日志',
            },
        ),
        migrations.CreateModel(
            name='CollectLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('create_timestamp', models.CharField(max_length=10, verbose_name='创建时间戳')),
                ('object_type', models.SmallIntegerField(blank=True, choices=[('博客', 0), ('文章', 1), ('视频', 2), ('评论', 3)], null=True, verbose_name='行为对象类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='行为对象ID')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='CommentLikeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('create_timestamp', models.CharField(max_length=10, verbose_name='创建时间戳')),
                ('object_type', models.SmallIntegerField(blank=True, choices=[('博客', 0), ('文章', 1), ('视频', 2), ('评论', 3)], null=True, verbose_name='行为对象类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='行为对象ID')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
            },
        ),
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('create_timestamp', models.CharField(max_length=10, verbose_name='创建时间戳')),
                ('object_type', models.SmallIntegerField(blank=True, choices=[('博客', 0), ('文章', 1), ('视频', 2), ('评论', 3)], null=True, verbose_name='行为对象类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='行为对象ID')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史',
            },
        ),
        migrations.CreateModel(
            name='LikeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('create_timestamp', models.CharField(max_length=10, verbose_name='创建时间戳')),
                ('object_type', models.SmallIntegerField(blank=True, choices=[('博客', 0), ('文章', 1), ('视频', 2), ('评论', 3)], null=True, verbose_name='行为对象类型')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='行为对象ID')),
                ('fk_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_like', to='article.Article')),
                ('fk_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_like', to='feed.Feed')),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞',
            },
        ),
    ]
