# Generated by Django 2.2 on 2023-02-04 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0003_auto_20230204_1855'),
        ('feed', '0002_auto_20230204_1855'),
        ('article', '0002_auto_20230204_1855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likelog',
            name='fk_weappuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historylog',
            name='fk_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.AddField(
            model_name='historylog',
            name='fk_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='historylog',
            name='fk_weappuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentlikelog',
            name='fk_article_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_comment_like', to='comment.ArticleComment'),
        ),
        migrations.AddField(
            model_name='commentlikelog',
            name='fk_feed_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_comment_like', to='comment.FeedComment'),
        ),
        migrations.AddField(
            model_name='commentlikelog',
            name='fk_weappuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='fk_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_collect', to='article.Article'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='fk_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_collect', to='feed.Feed'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='fk_weappuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_collect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='fk_weappuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
