# Generated by Django 2.2 on 2023-02-04 18:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('preview', models.TextField(max_length=60, verbose_name='文章预览')),
                ('origin', models.TextField(max_length=20, verbose_name='文章来源')),
                ('cover', models.CharField(max_length=200, verbose_name='封面链接')),
                ('visitor', models.IntegerField(default=0, verbose_name='浏览数量')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数量')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5, verbose_name='标签名字')),
                ('num', models.IntegerField(default=0, verbose_name='引用次数')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
    ]
