# Generated by Django 2.2 on 2023-02-04 18:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spider_date', models.DateTimeField(auto_now=True, verbose_name='爬取时间')),
                ('tid', models.CharField(blank=True, max_length=25, null=True, verbose_name='第三方平台ID')),
                ('create_time', models.CharField(max_length=20, verbose_name='发布时间')),
                ('create_timestamp', models.IntegerField(verbose_name='创建时间戳')),
                ('modify_timestamp', models.IntegerField(verbose_name='修改时间戳')),
                ('is_modified', models.BooleanField(default=False, verbose_name='是否已修改')),
                ('content', ckeditor.fields.RichTextField(verbose_name='说说内容')),
                ('convert_content', ckeditor.fields.RichTextField(verbose_name='转换后内容(剔除表情符号)')),
                ('picture_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='媒体数量')),
                ('visitor_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览量')),
                ('like_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞量')),
                ('forward_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='转发数')),
                ('comment_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('is_external', models.BooleanField(blank=True, default=False, null=True, verbose_name='来自第三方')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20, verbose_name='发布时间')),
                ('title', models.CharField(default='', max_length=20, verbose_name='热点标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='说说内容')),
                ('visitor', models.IntegerField(verbose_name='浏览量')),
                ('spiderDate', models.DateTimeField(auto_now=True, verbose_name='爬取时间')),
                ('origin', models.CharField(blank=True, max_length=20, null=True, verbose_name='新闻来源')),
                ('cover', models.CharField(max_length=200, verbose_name='封面链接')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='原文链接')),
                ('recommend', models.BooleanField(default=False, verbose_name='推荐热搜')),
                ('commerce', models.BooleanField(default=False, verbose_name='商业热搜')),
                ('top', models.BooleanField(default=False, verbose_name='置顶热搜')),
                ('tag', models.CharField(choices=[('hot', '热点'), ('news', '新闻'), ('article', '文章')], default='news', max_length=10, verbose_name='信息类型')),
            ],
            options={
                'verbose_name': '学校新闻',
                'verbose_name_plural': '学校新闻',
            },
        ),
    ]
