# Generated by Django 2.2 on 2023-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='image', max_length=6, verbose_name='媒体类型')),
                ('url', models.CharField(max_length=200, verbose_name='媒体地址')),
                ('target', models.CharField(max_length=50, null=True, verbose_name='目标页面')),
                ('login', models.BooleanField(default=False, verbose_name='需要登录')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=20, verbose_name='菜单图标')),
                ('index', models.IntegerField(verbose_name='菜单索引')),
                ('color', models.CharField(max_length=10, verbose_name='菜单颜色')),
                ('badge', models.IntegerField(choices=[(0, '无消息提示'), (1, '展示圆点')], default=0, verbose_name='消息图标')),
                ('name', models.CharField(max_length=10, verbose_name='菜单名称')),
                ('enable', models.BooleanField(default=False, verbose_name='是否启用')),
                ('target', models.CharField(max_length=25, verbose_name='目标页面')),
                ('login', models.BooleanField(default=True, verbose_name='需要登录')),
                ('permission', models.IntegerField(choices=[(0, '访客'), (1, '用户'), (2, '班级'), (3, '学院'), (4, '特殊权限'), (5, '超管')], default=0, verbose_name='最低权限')),
            ],
            options={
                'verbose_name': '首页菜单',
                'verbose_name_plural': '首页菜单',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menuNum', models.IntegerField(default=8, unique=True, verbose_name='菜单数量')),
                ('bannerNum', models.IntegerField(default=4, unique=True, verbose_name='轮播数量')),
                ('comment', models.BooleanField(default=False, unique=True, verbose_name='开启评论')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设置信息',
                'verbose_name_plural': '设置信息',
            },
        ),
    ]
