# Generated by Django 2.2 on 2023-02-04 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('create_timestamp', models.IntegerField(verbose_name='创建时间戳')),
                ('update_timestamp', models.IntegerField(verbose_name='更新时间戳')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='话题名称')),
                ('introduction', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='导语')),
                ('is_main', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否主索引')),
                ('refer_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='引用次数')),
                ('visitor_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读次数')),
                ('heat', models.IntegerField(blank=True, default=0, null=True, verbose_name='热度')),
                ('recommend', models.BooleanField(blank=True, default=False, null=True, verbose_name='推荐热搜')),
                ('commerce', models.BooleanField(blank=True, default=False, null=True, verbose_name='商业热搜')),
                ('top', models.BooleanField(blank=True, default=False, null=True, verbose_name='置顶热搜')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
            },
        ),
    ]
