# Generated by Django 2.2 on 2023-02-04 18:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.IntegerField(blank=True, null=True, verbose_name='序号(第几条评论)')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='评论内容')),
                ('convert_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='转换后内容(剔除表情符号)')),
                ('timestamp', models.IntegerField(blank=True, null=True, verbose_name='时间戳')),
                ('create_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间')),
                ('is_reply', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否评论的回复')),
                ('reply_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='回复数量')),
                ('picture_num', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='图片数量')),
                ('like_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数量')),
                ('to_id', models.IntegerField(blank=True, null=True, verbose_name='回复ID')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.IntegerField(blank=True, null=True, verbose_name='序号(第几条评论)')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='评论内容')),
                ('convert_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='转换后内容(剔除表情符号)')),
                ('timestamp', models.IntegerField(blank=True, null=True, verbose_name='时间戳')),
                ('create_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间')),
                ('is_reply', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否评论的回复')),
                ('reply_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='回复数量')),
                ('picture_num', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='图片数量')),
                ('like_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数量')),
                ('to_id', models.IntegerField(blank=True, null=True, verbose_name='回复ID')),
                ('is_external', models.BooleanField(blank=True, default=True, null=True, verbose_name='第三方')),
            ],
            options={
                'verbose_name': 'Feed评论',
                'verbose_name_plural': 'Feed评论',
            },
        ),
    ]
