# Generated by Django 2.2 on 2023-02-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='fk_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed'),
        ),
    ]
