# Generated by Django 2.2 on 2023-02-04 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0002_auto_20230204_1855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_feedcomment_fk_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='fk_qquser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AnonmyousQQ'),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='fk_weappuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='fk_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='fk_weappuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
