# Generated by Django 2.2 on 2023-02-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='图片顺序')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('height', models.SmallIntegerField(blank=True, null=True, verbose_name='高度')),
                ('width', models.SmallIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('type', models.SmallIntegerField(blank=True, choices=[('图片', 0), ('视频', 1)], default=0, null=True, verbose_name='类型')),
                ('url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('is_external', models.BooleanField(blank=True, default=False, null=True, verbose_name='来自外部')),
            ],
            options={
                'verbose_name': 'Article评论图片',
                'verbose_name_plural': 'Article评论图片',
            },
        ),
        migrations.CreateModel(
            name='FeedCommentPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='图片顺序')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('height', models.SmallIntegerField(blank=True, null=True, verbose_name='高度')),
                ('width', models.SmallIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('type', models.SmallIntegerField(blank=True, choices=[('图片', 0), ('视频', 1)], default=0, null=True, verbose_name='类型')),
                ('url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('is_external', models.BooleanField(blank=True, default=False, null=True, verbose_name='来自外部')),
            ],
            options={
                'verbose_name': 'Feed评论图片',
                'verbose_name_plural': 'Feed评论图片',
            },
        ),
        migrations.CreateModel(
            name='FeedPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='图片顺序')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('height', models.SmallIntegerField(blank=True, null=True, verbose_name='高度')),
                ('width', models.SmallIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('type', models.SmallIntegerField(blank=True, choices=[('图片', 0), ('视频', 1)], default=0, null=True, verbose_name='类型')),
                ('url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('is_external', models.BooleanField(blank=True, default=False, null=True, verbose_name='来自外部')),
                ('fk_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='feed.Feed')),
            ],
            options={
                'verbose_name': 'Feed图片',
                'verbose_name_plural': 'Feed图片',
            },
        ),
    ]
