# Generated by Django 2.2 on 2023-02-04 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0003_auto_20230204_1855'),
        ('user', '0001_initial'),
        ('photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpicture',
            name='fk_qquser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AnonmyousQQ'),
        ),
        migrations.AddField(
            model_name='feedpicture',
            name='fk_weappuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedcommentpicture',
            name='fk_feed_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='comment.FeedComment'),
        ),
        migrations.AddField(
            model_name='feedcommentpicture',
            name='fk_qquser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AnonmyousQQ'),
        ),
        migrations.AddField(
            model_name='feedcommentpicture',
            name='fk_weappuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlecommentpicture',
            name='fk_article_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.ArticleComment'),
        ),
        migrations.AddField(
            model_name='articlecommentpicture',
            name='fk_qquser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AnonmyousQQ'),
        ),
        migrations.AddField(
            model_name='articlecommentpicture',
            name='fk_weappuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
